### ISSUE TITLE
Basic question about the use of my_policy

### ISSUE THREAD

**Issue by JSchuurmans** [deepmind/jmp#22]
Hi,

Thanks for creating this amazing functionality!

I have a basic question about the use of policy functions to set certain precision levels.
As stated in the example of your README.md:
```python
def layer(params, x):
  params, x = my_policy.cast_to_compute((params, x))
  w, b = params
  y = x @ w + b
  return my_policy.cast_to_output(y)
```

I am new to JAX, but the first thing I learned is that JAX likes pure functions.
**Does the use of my_policy violate the pure functions paradigm?**

Should it become:
```python
def layer(params, x, my_policy):
  params, x = my_policy.cast_to_compute((params, x))
  w, b = params
  y = x @ w + b
  return my_policy.cast_to_output(y)
```

The function can be jitted by using `partial`. 
```python
from functools import partial
layer_compiled = jit(partial(layer, my_policy=my_policy))
```

## Fundamental question
A more fundamental question (which I maybe need to ask at [JAX](https://github.com/google/jax) ) is: 
**How should functions as input to functions be handled in JAX?**
```python
func_a(x,w,func):
  ...

func_a_compiled = jit(partial(func_a, func=func_b))
```
In order to jit this, I came up with the `partial` solution above. I assume your use of my_policy is valid, as you probably have more experience with JAX. But that creates some magic, which is undesirable for my use case. Is the `jit(partial())` solution valid or is there a better way to handle functions as input to functions?

Have a nice day! J

**Comment by tomhennigan** [comment]
Hi @JSchuurmans , `jmp.Policy` is an immutable dataclass, so as long as you don't re-assign it (e.g. `my_policy = something_else`) in your program it is fine to close over it as a constant (and the behaviour under JAX transforms is well defined, the value is a constant).

The JAX solution for passing non-JAX types (e.g. functions) to jitted functions is to either use partial (as you have done) or to use `static_argnums=(0, 1, ...)` to specify which arguments JAX should treat as static values.

Another common pattern for this is to use objects to hold configuration, and to use `jit` on bound methods (in the constructor) of those objects:

```python
class Experiment:
  def __init__(self):
    # Fine for JAX since this is a constant.
    self.policy = jmp.Policy(..)
    # This is equivalent to `jax.jit(partial(Experiment.forward, self))`.
    self.forward = jax.jit(self.forward)

  def forward(self, params, x):
    my_policy = self.policy
    params, x = my_policy.cast_to_compute((params, x))
    w, b = params
    y = x @ w + b
    return my_policy.cast_to_output(y)

e = Experiment()
e.forward(params, x)
```

**Comment by JSchuurmans** [comment]
@tomhennigan, thank you for answering both questions. The suggested object gave me a good idea for my implementation!
