### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mariogeiger** [deepmind/jmp#34]
Hi, Could you make a new release? I have a bug with python 3.11 and I think that if you make a new release it would fix it.

<img width="880" alt="Screenshot 2023-01-16 at 8 49 39 PM" src="https://user-images.githubusercontent.com/333780/212755950-29415f85-3e16-4524-99e8-3cf8a627df1b.png">

**Comment by tomhennigan** [comment]
Hi @mariogeiger , thanks for the nudge. I will cut a new release tomorrow.

**Comment by tomhennigan** [comment]
I've pushed 0.0.3 to pypi: https://pypi.org/project/jmp/0.0.3/
