### ISSUE TITLE
Example on JMP x Flax?

### ISSUE THREAD

**Issue by llCurious** [deepmind/jmp#45]
Hey, this mixed-precision functionality is awesom. I note the haiku example and wonder if there is a example on using JMP on Flax?

**Comment by llCurious** [comment]
@tomhennigan Do you have any ideas or comments?

**Comment by tomhennigan** [comment]
I believe Flax have their own mixed precision support, I am not aware of examples of them using or integrating JMP.

Their imagenet example includes an example of mixed precision training https://github.com/google/flax/tree/main/examples/imagenet/.
